services:
  - type: web
    name: fitwell-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fitwell-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://fitwell-frontend.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://fitwell-frontend.onrender.com"

  - type: static
    name: fitwell-frontend
    env: static
    buildCommand: cd fitwell-frontend && npm install && npm run build
    publishDir: fitwell-frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: fitwell-backend
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: fitwell-db
    plan: free
